version: '3.2'

services:
  odoo-11.0:
    tty: true
    stdin_open: true
    build: ./
    ports:
      - 8069
    depends_on:
      - db
    volumes:
      - type: bind
        source: /opt/odoo-addons/11.0
        target: /opt/odoo-addons/11.0
      - type: volume
        source: odoo-data-11.0
        target: /var/lib/odoo
      - type: volume
        source: extra-addons-11.0
        target: /mnt/extra-addons
    environment:
      - DB_ENV_POSTGRES_PASSWORD=odoo11
      - DB_ENV_POSTGRES_USER=odoo11
      - DB_ENV_NAME=odoodb
      - ODOO_ENV_ADMIN_PASSWD=admin-odoo11
      - ODOO_ENV_LOG_HANDLER=:INFO
  db:
    image: postgres:10
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=odoo11
      - POSTGRES_PASSWORD=odoo11
      - POSTGRES_DB=postgres
    volumes:
      - ./docker-init:/docker-entrypoint-initdb.d/
