# Composition for development

version: '2.01'

services:
  odoo:
    tty: true
    stdin_open: true
    build: ./
    ports:
      - 8069
    depends_on:
      - db
    volumes:
      - "data-odoo:/data/odoo"
      - "extra-addons-11.0:/mnt/extra-addons"
    environment:
      - DB_USER=odoo
      - DB_PASS=odoo
      - DB_NAME=odoodb
      - ADMIN_PASSWD=123654@@
      - RUNNING_ENV=dev
      - LOG_HANDLER=:INFO

  # can be useful for dev when longpolling is required
#  nginx:
#    image: camptocamp/odoo-nginx:11.0-1.3.0
#    ports:
#      - 80:80
#    depends_on:
#      - odoo

volumes:
  data-odoo:
  data-db:
  # store pytest cache, allowing to use --lf or --ff (replay last or first failures)
  data-odoo-pytest-cache: